# Generated by Django 2.2.11 on 2020-04-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='feeling_good',
            field=models.BooleanField(default=True),
        ),
    ]
